services:
  - type: web
    name: zenos-md-v1
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 20.0.0
